/*
 * Generated by AI-Driven SailPoint IIQ Rule Generator
 *
 * Rule Type: BuildMap
 * Description: This rule maps a source attribute to an identity attribute.
 */
import sailpoint.object.Identity;
import sailpoint.object.Link;
import java.util.Map;

// Get the source attribute value from the map
String sourceValue = (String) map.get("{{ source_attribute }}");

// Set the identity attribute value
if (sourceValue != null) {
    identity.setAttribute("{{ identity_attribute }}", sourceValue);
}

return identity;